# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'  
    args: 
    - '-c'
    - | 
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
    - '-c'
    - |
        case $BRANCH_NAME in 
        (dev|prod)
          export ENVIRONMENT=$BRANCH_NAME
        ;; 
        (*)
          export ENVIRONMENT=dev
        ;;
        esac
                
        cp config.google.tmpl config.google.tfbackend
        sed -i s/ORG/$$ORG/g config.google.tfbackend
        sed -i s/BUCKET_ENVIRONMENT/$$BUCKET_ENVIRONMENT/g config.google.tfbackend
        sed -i s/ENVIRONMENT/$$ENVIRONMENT/g config.google.tfbackend
        terraform init -backend-config=config.google.tfbackend
    env:
    - 'ORG=bodendava'
    - 'BUCKET_ENVIRONMENT=bld'
        
  # [START tf-plan]
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
    - '-c'
    - |
        case $BRANCH_NAME in 
        (dev|prod)
          export ENVIRONMENT=$BRANCH_NAME
        ;; 
        (*)
          export ENVIRONMENT=dev
        ;;     
        esac   
        terraform plan  -var-file=$$ENVIRONMENT.tfvars
  # [END tf-plan]
  # [START tf-apply]
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
        case $BRANCH_NAME in 
        (dev|prod)
          terraform apply -var-file=$BRANCH_NAME.tfvars -auto-approve
        ;; 
        (*)
          echo "***************************** SKIPPING APPLYING *******************************"
          echo "Branch '$BRANCH_NAME' is not valid branch for applying"
          echo "*******************************************************************************"
        ;;
        esac
# [END tf-apply]     
options:
  logging: CLOUD_LOGGING_ONLY